
title: wahyu6070
email: gwtsendangrejo6070@gmail.com
description: "Hello my name is wahyu or commonly known (wahyu6070), this is my official page."
baseurl: "/"
url: "wahyu6070.github.io"
twitter_username: wahyu6070
github_username:  wahyu6070

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
