title : wahyu6070 - Documentation
baseurl: "/"
url: "https://wahyu6070.github.io"
permalink: /:categories/:year/:month/:title

plugins:
  - jekyll-paginate
  
# Pagination 
paginate: 10
paginate_path: "/blog/blog-:num"
    
exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

